#####################################################################
# Generals                                                          #
#####################################################################

set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Options
set-option -sg escape-time 10
set-option -sa terminal-overrides ',XXX:RGB'

# Start index with 1
set -g base-index 1
set -g pane-base-index 1

# VIM
set-window-option -g mode-keys vi

#####################################################################
# Mapping                                                           #
#####################################################################

# Remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix M-a
bind-key M-a send-prefix

# Reload config
bind r source ~/.tmux.conf

# Rotate Window
bind o rotate-window

# Splits
bind g split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

# Move pane with Control (no prefix)
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

# resize
bind -n M-H resize-pane -L 10
bind -n M-J resize-pane -D 5
bind -n M-K resize-pane -U 5
bind -n M-L resize-pane -R 10

# Kill Selected Pane
bind-key -n M-x kill-pane

# Switch windows alt+number
bind-key -n M-1 if-shell 'tmux select-window -t 1' '' 'new-window -t 1'
bind-key -n M-2 if-shell 'tmux select-window -t 2' '' 'new-window -t 2'
bind-key -n M-3 if-shell 'tmux select-window -t 3' '' 'new-window -t 3'
bind-key -n M-4 if-shell 'tmux select-window -t 4' '' 'new-window -t 4'
bind-key -n M-5 if-shell 'tmux select-window -t 5' '' 'new-window -t 5'
bind-key -n M-6 if-shell 'tmux select-window -t 6' '' 'new-window -t 6'
bind-key -n M-7 if-shell 'tmux select-window -t 7' '' 'new-window -t 7'
bind-key -n M-8 if-shell 'tmux select-window -t 8' '' 'new-window -t 8'
bind-key -n M-9 if-shell 'tmux select-window -t 9' '' 'new-window -t 9'
bind-key -n M-0 if-shell 'tmux select-window -t 10' '' 'new-window -t 10'

# move window to other pane
bind-key -n M-! join-pane -t :1
bind-key -n M-@ join-pane -t :2
bind-key -n M-'#' join-pane -t :3
bind-key -n M-'$' join-pane -t :4
bind-key -n M-'%' join-pane -t :5
bind-key -n M-'^' join-pane -t :6
bind-key -n M-'&' join-pane -t :7
bind-key -n M-'*' join-pane -t :8
bind-key -n M-'(' join-pane -t :9
bind-key -n M-')' join-pane -t :10

#####################################################################
# Status line                                                       #
#####################################################################

set-option -g status-position bottom 
set-option -g status-style "fg=colour20,bg=colour18"
set-option -g status-interval 1
set -g status-justify left
setw -g window-status-separator '  '
set -g window-status-format "#[fg=colour20] #I #W #[default]"
set -g window-status-current-format "#[bg=colour08,fg=colour00] #I #[bg=colour19,fg=colour20] #W #[default]"
set -g status-right '#[bg=colour19,fg=colour20] #(TZ="Asia/Vladivostok" date +%%D) #[bg=colour08,fg=colour00] #(TZ="Asia/Vladivostok" date +%%H:%%M:%%S) #[default]'
