theme = "ayu_evolve"

[editor]
line-number = "relative"
scroll-lines = 1
scrolloff = 7
color-modes = true
bufferline = "always"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.search]
smart-case = true

[editor.indent-guides]
render = true
character = "▏"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[keys.normal]
"+" = "expand_selection"
"minus" = "shrink_selection"
"esc" = ["collapse_selection", "keep_primary_selection"]

"[" = { "b" = "goto_previous_buffer" }
"]" = { "b" = "goto_next_buffer" }

"K" = "hover"
"A-k" = "keep_selections"

"0" = { c = { "r" = ":config-reload", "o" = ":config-open" }, i = { d =  ["normal_mode", ":insert-output date +'%Y-%m-%d %R' | tr '\n' '\\0' ", "collapse_selection", "insert_at_line_end" ]  } }

[keys.normal.space]
"q" = ":buffer-close"

[keys.select]
"o" = "flip_selections"